services:
  db:
    image: postgres:15
    restart: always
    container_name: log430-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magasin_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: log430-server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/magasin_db"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  client1:
    build: ./client
    container_name: log430-client1
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped

  client2:
    build: ./client
    container_name: log430-client2
    ports:
      - "5174:80"
    depends_on:
      - server
    restart: unless-stopped

  client3:
    build: ./client
    container_name: log430-client3
    ports:
      - "5175:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  db-data:
