apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client1
  template:
    metadata:
      labels:
        app: client1
    spec:
      containers:
      - name: client1
        image: log430-client:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client1
spec:
  type: NodePort
  selector:
    app: client1
  ports:
  - port: 80
    nodePort: 30001
---
# Repeat similar blocks for client2 and client3 with different names
